version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: always
    volumes:
      - wp-v:/var/www/html
    ports:
      - 443:443
    networks:
      - my-network
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    restart: always
    volumes:
      - db:/var/lib/mysql
      - wp-v:/var/www/html
    networks:
      - my-network
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network
    env_file:
      - .env


  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wp-v:/var/www/html
    networks:
      - my-network

  ftp-server:
    build: requirements/bonus/ftp
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wp-v:/var/www/html"
    networks:
      - my-network
    restart: always
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    expose:
     - "9000"
    networks:
      - my-network

  static:
    container_name: static
    build: requirements/bonus/static
    restart: always
    expose:
     - "8080"
    networks:
      - my-network

  cadvisor:
    container_name: cadvisor
    build: requirements/bonus/cadvisor
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my-network

volumes:
  wp-v:
    driver: local
    driver_opts:
      device: /home/gfantech/data/wordpress
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /home/gfantech/data/mariadb
      o: bind
      type: none

networks:
  my-network:
